language: cpp
before_script:
- mkdir -p build
- cd build
- cmake ..
script:
- cmake --build . --config Release --target install
jobs:
  include:
  - name: Check Source Formatting
    os: linux
    dist: focal
    before_script: 
    script:
    - npm install
    - npm run format -- --dry-run -Werror
  - name: Windows + VS2017
    os: windows
    cache:
      timeout: 1000
      directories:
      - C:\Program Files\Epic Games\UE_4.26
      - C:\Program Files (x86)\Epic Games\Launcher
    install:
    - choco install httpie
    - ./travis-get-ue.sh
    before_script:
    - export CESIUM_UNREAL_VERSION=$(git describe)
    - mkdir -p extern/build
    - cd extern/build
    - cmake .. -A x64
    script:
    - cmake --build . --config Release --target install -- /maxcpucount:4
    - cd ../..
    - rm -rf extern
    - export CLONEDIR=$PWD
    - cd /c/Program\ Files/Epic\ Games/UE_4.26/Engine/Build/BatchFiles
    - ./RunUAT.bat BuildPlugin -Plugin="$CLONEDIR/CesiumForUnreal.uplugin" -Package="$CLONEDIR/../packages/CesiumForUnreal" -CreateSubFolder
    - cd "$CLONEDIR/../packages"
    - 7z a CesiumForUnreal-${CESIUM_UNREAL_VERSION}.zip "CesiumForUnreal\"
    - aws s3 cp CesiumForUnreal-${CESIUM_UNREAL_VERSION}.zip s3://builds-cesium-unreal/
    - export PACKAGE_LINK=$(aws --region us-east-1 s3 presign s3://builds-cesium-unreal/CesiumForUnreal-${CESIUM_UNREAL_VERSION}.zip --expires-in 315360000)
    - http POST "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/statuses/${TRAVIS_COMMIT}" "Authorization:token ${GITHUB_TOKEN}" state=success context=plugin-package "target_url=${PACKAGE_LINK}"
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
env:
  global:
  - secure: PbZbyzY3rqCYG9AysPOtC616bFyX2RH2XRg6DJ9CrRQmcpifDcMJAUEFl3Z2Xcl1OeUyAeZP6lxYO55436jmQMnmT46oFIl4CNIh1pN88NwYsMZ6MDCt50rPy+PvPQldxYhIhTfeNVuWrscrCodKgE2ewSvu8IjwSeJfs85ZUxvH8Eme7CYbGqoB4HJEQG8Sdc2VH5z0C6Fy+fGV1Q0W0ItH2A6UKpkRcGrXnvPxWr+AJkI91DdOlNiHrrr+Bi71tYp3DXVz+YtaS9fa/jO9bEdBV56hdJgG6NoH0bnRyTVAqgjMawecMr+1i+m7S7G4G3qwivXSsS2k5nQE8jsf4pLIzb1GyDNe2Lo/gnRcRhiLCW01SwIl+W3VozKzSofs7Wi+kn/Hkbe15f35NsOnmaqfNRRWAChAEovs4NLsnzpUwKwXmxOPDNYsgpnpB3YNycvIDkvCYcoHvrBJO4ytwrG1gXTKjfg5CChwjSoLbtxVEpyUb1W/XL2KgcECDoCkja8Xp+QUdUn/kaN8vpo7sVetKDK+BURlqTCQWGkwmo1dje7XrZUwCX+61+FiQBJu6QmUHnYFDT6P3wyKNZ522ETeqnfdOjzekFQnMDTtOi5Kv7L6bdYS1pG3fhKk2slc3QQuFgmHNfl8JFofjBgGW7sAKl0k5uqKDYf8V6WPuMQ=
  - secure: M9boPWBI7TcautD/9VwacCeQAh3ssMArP4x7sLpgGTbh1F/mo7alnicItdR0rSqD6F9japzS9NP18JX1nuUJsRQHG7wb0UayKN+Mxnwx0MkGcZ5/r2j64OTLDXN8T2Gqc3w2LBqFkmFLctHE5hpfNxmy2Z8cE4MRQnaSxMqQhOffw7iRPPp72u16oh4Ub+dASMl+ETtJthnwwEn4STMo1YUdf9sSiYlSLr4KixxFnMJKyYwYyVCbZKqZeIHPH4x1Me+EPg9bsl6Tox3jp46QvznfobC2SYjaDAkpzXkQkPftZ7FBE76jHybueEhWTGf7b8B2X36IdBGVKm+HZmtO5UndJamTUPB/DsWqfM0w54zZ1UOmXZOuxYgp008wHBE0DZSZ49FHq1zdVmXDdx5MMe4q6YV+F479UCHsOurK+63/Ap+DYK7mDmMd089XIm7WyaPubhXbKdo3w29Lynt9mhxsUpcGaIovoXkxqDP60ziM0/sYNbo95uTn5NoxbUsw6XPHs7ahymMXdf6+5z3t2Ecu8UuVZCKUk+4J003hPkUkj/Z4yM/A9aRdUgp8EkW6/Ro9HubF0A7JBtO+G6JNmjXKqJ82kMdU2MojMHKuVSKHItS19BHtYqgFp+QicmNIFf/EacvKKxbJQyPBLT+dAtEjcHNwlWDL66m1FFk/MVE=
